{
	name: "想い繋がる 和の国神んぐ！",
	cardno: 9950,
	imageno: 12299,
	imageno_prefix: "F2xTuL_",
	hp: 2585,
	atk: 4314,
	cost: 57,
	attr: [0,2],
	species: [1],
	islegend: true,
	ape: "周年記念精霊(5周年)",
	as1: {
		desc: "<連撃>4チェインで敵単体を4回連続攻撃(250%)、デッキ内の精霊が持つ属性数が多いほどさらにアップ(60%)(上限値:5段階)",
		proc: add_cond(ChainDualAttack(2.5, 4, 4), as_deckinattr_num(0, 0.6)),
	},
	ss1: {
		desc: "<ダブルスキル付与>2ターン溜めた後、8ターンの間、味方一人にSPスキル使用回数+1の効果を付与する(SPスキル使用回数アップの効果は重複しません)",
		turn: 8,
		charged: 2,
		proc: [ss_toselect_one(ss_doubleskill_all(8))],
	},
	awakes: [
		Abstate_invalid("ss_sealed"),
		Panel_boost([1,0,0,0,0,],4),
		Attr_statusup(0,200, [1,0,1,0,0,]),
		Attr_statusup(200,0, [1,0,1,0,0,]),
		Fastskill(3),
		Attr_relief([1,1,1,1,1,],20),
		Fastskill(3),
		Attr_statusup_subattr(0, 500),
		Attr_statusup_subattr(500, 0),
		Awake_noeffect("心眼・怒",1),
	],
	as2: {
		desc: "<連撃>4チェインで敵単体を4回連続攻撃(350%)、デッキ内の精霊が持つ属性数が多いほどさらにアップ(60%)(上限値:5段階)",
		proc: add_cond(ChainDualAttack(3.5, 4, 4), as_deckinattr_num(0, 0.6)),
	},
	ss2: {
		desc: "<ダブルスキル付与>2ターン溜めた後、8ターンの間、味方一人にSPスキル使用回数+1の効果を付与する(SPスキル使用回数アップの効果は重複しません)",
		turn: 8,
		charged: 2,
		proc: [ss_toselect_one(ss_doubleskill_all(8))],
	},
	Lawake: [
		Attr_statusup(0,300, [1,0,1,0,0,]),
		Abstate_invalid("as_sealed"),
	],
}